"""GitHub push and draft pull request via REST API."""

from __future__ import annotations

import json
import re
import subprocess
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from config import Settings, get_settings
from tools.agent_console import log_detail, log_step
from tools.git_commit_tool import get_git_root
from tools.subprocess_log import run_logged

GITHUB_API = "https://api.github.com"
AI_SAFETY_NOTE = (
    "This PR was generated by an autonomous AI coding agent and requires "
    "human review before merge."
)


@dataclass(frozen=True)
class GitHubRepoTarget:
    """Owner, repo, and base branch for GitHub operations."""

    owner: str
    repo: str
    base_branch: str
    remote_url: str


@dataclass(frozen=True)
class PullRequestResult:
    """Created or existing pull request."""

    number: int
    url: str
    html_url: str
    draft: bool
    already_existed: bool = False


def parse_github_remote(remote_url: str) -> tuple[str, str] | None:
    """Extract (owner, repo) from HTTPS or SSH GitHub remote URLs."""
    url = remote_url.strip().rstrip("/")
    if url.endswith(".git"):
        url = url[:-4]

    # git@github.com:owner/repo
    ssh = re.match(r"git@github\.com:([^/]+)/([^/]+)$", url)
    if ssh:
        return ssh.group(1), ssh.group(2)

    # https://github.com/owner/repo
    https = re.match(r"https?://github\.com/([^/]+)/([^/]+)$", url)
    if https:
        return https.group(1), https.group(2)

    return None


def get_remote_url(repo_path: str | Path, remote: str = "origin") -> str:
    """Return git remote URL for the repository."""
    git_root = get_git_root(repo_path)
    if git_root is None:
        raise RuntimeError("Not a git repository.")

    result = subprocess.run(
        ["git", "-C", str(git_root), "remote", "get-url", remote],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"Remote '{remote}' not found: {result.stderr.strip() or result.stdout.strip()}"
        )
    return result.stdout.strip()


def resolve_github_target(
    repo_path: str | Path,
    settings: Settings | None = None,
) -> GitHubRepoTarget:
    """
    Resolve GitHub owner/repo from env or git remote.

    Env GITHUB_OWNER and GITHUB_REPO override parsed remote.
    """
    settings = settings or get_settings()
    remote_url = get_remote_url(repo_path)
    parsed = parse_github_remote(remote_url)

    owner = (settings.github_owner or "").strip()
    repo = (settings.github_repo or "").strip()
    if not owner or not repo:
        if parsed is None:
            raise RuntimeError(
                f"Could not parse GitHub owner/repo from remote: {remote_url}. "
                "Set GITHUB_OWNER and GITHUB_REPO in .env."
            )
        owner, repo = parsed

    base = (settings.github_base_branch or "main").strip() or "main"
    return GitHubRepoTarget(
        owner=owner,
        repo=repo,
        base_branch=base,
        remote_url=remote_url,
    )


def _api_request(
    method: str,
    path: str,
    token: str,
    *,
    body: dict[str, Any] | None = None,
) -> dict[str, Any]:
    url = f"{GITHUB_API}{path}"
    data = None
    headers = {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {token}",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "ai-dev-agent",
    }
    if body is not None:
        data = json.dumps(body).encode("utf-8")
        headers["Content-Type"] = "application/json"

    request = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            raw = response.read().decode("utf-8")
            return json.loads(raw) if raw else {}
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"GitHub API {exc.code}: {detail}") from exc


def find_open_pr_for_branch(
    owner: str,
    repo: str,
    head_branch: str,
    token: str,
) -> dict[str, Any] | None:
    """Return existing open PR dict if one exists for head branch."""
    head = urllib.parse.quote(f"{owner}:{head_branch}", safe="")
    path = f"/repos/{owner}/{repo}/pulls?state=open&head={head}"
    result = _api_request("GET", path, token)
    if isinstance(result, list) and result:
        return result[0]
    return None


def push_branch(
    repo_path: str | Path,
    branch_name: str,
    token: str,
    *,
    settings: Settings | None = None,
) -> str:
    """
    Push branch to GitHub origin using token authentication.

    Returns the push remote URL (token redacted in logs externally).
    """
    git_root = get_git_root(repo_path)
    if git_root is None:
        raise RuntimeError("Not a git repository.")

    target = resolve_github_target(repo_path, settings)
    push_url = f"https://x-access-token:{token}@github.com/{target.owner}/{target.repo}.git"

    log_step("Pushing branch to GitHub…", style="cyan")
    log_detail(f"  $ git push origin {branch_name}")
    result = run_logged(
        ["git", "-C", str(git_root), "push", push_url, branch_name],
        timeout=600,
        echo_command=False,
    )
    if result.returncode != 0:
        err = result.stderr.strip() or result.stdout.strip()
        raise RuntimeError(f"git push failed: {err}")

    return f"https://github.com/{target.owner}/{target.repo}.git"


def create_draft_pr(
    owner: str,
    repo: str,
    title: str,
    head_branch: str,
    base_branch: str,
    body: str,
    token: str,
) -> dict[str, Any]:
    """Create a draft pull request via GitHub REST API."""
    path = f"/repos/{owner}/{repo}/pulls"
    payload = {
        "title": title,
        "head": head_branch,
        "base": base_branch,
        "body": body,
        "draft": True,
    }
    return _api_request("POST", path, token, body=payload)


def get_pr_url(response: dict[str, Any]) -> str:
    """Extract PR HTML URL from API response."""
    return str(response.get("html_url") or response.get("url") or "")


def get_pr_number(response: dict[str, Any]) -> int:
    """Extract PR number from API response."""
    return int(response.get("number") or 0)


def format_pr_title(task_description: str) -> str:
    """PR title: fix: {task summary}."""
    summary = task_description.strip().lower()
    summary = re.sub(r"\s+", " ", summary)
    if not summary:
        summary = "apply agent patch"
    return f"fix: {summary}"


def format_pr_title_for_jira(issue_key: str, summary: str) -> str:
    """PR title: fix(ABC-123): summary."""
    key = issue_key.strip().upper()
    text = re.sub(r"\s+", " ", summary.strip()) or "apply agent patch"
    return f"fix({key}): {text}"


def format_pr_body_for_jira(
    *,
    issue_key: str,
    summary: str,
    root_cause: str,
    changed_files: list[str],
    validation_status: str,
    validation_commands: list[str] | None = None,
) -> str:
    """PR body for Jira batch workflow."""
    files_md = "\n".join(f"- `{f}`" for f in changed_files) or "- (none)"
    cmds = validation_commands or []
    cmds_md = "\n".join(f"- `{c}`" for c in cmds) or "- (none)"
    key = issue_key.strip().upper()

    return f"""## Jira issue
**{key}** — {summary}

## Root cause
{root_cause or "(not recorded)"}

## Changed files
{files_md}

## Validation commands
{cmds_md}

## Validation result
{validation_status or "skipped"}

## AI safety note
{AI_SAFETY_NOTE}

---
*Draft PR created by the autonomous AI coding agent. Human review required before merge.*
"""


def format_pr_body(
    *,
    task_description: str,
    root_cause: str,
    recommended_fix: str,
    changed_files: list[str],
    validation_commands: list[str],
    validation_status: str,
    commit_hash: str,
) -> str:
    """Build markdown PR body with required sections."""
    files_md = "\n".join(f"- `{f}`" for f in changed_files) or "- (none)"
    cmds_md = "\n".join(f"- `{c}`" for c in validation_commands) or "- (none)"

    return f"""## Task
{task_description}

## Root cause
{root_cause or "(not recorded)"}

## Recommended fix
{recommended_fix or "(not recorded)"}

## Changed files
{files_md}

## Validation commands
{cmds_md}

## Validation result
{validation_status or "skipped"}

## Commit
`{commit_hash or "(none)"}`

## AI safety note
{AI_SAFETY_NOTE}
"""
